<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>SMART_ERP</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Resources\SmartERP.ico</ApplicationIcon>
    <NoWarn>NU1701</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Resources\SmartERP.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LiveCharts.Wpf" Version="0.9.7" />
    <PackageReference Include="MySqlConnector" Version="2.6.2" />
    <PackageReference Include="ClosedXML" Version="0.104.2" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove=".backups_usuarios_20260903_144330\**\*.cs" />
    <None Include=".backups_usuarios_20260903_144330\**\*" />
    <Compile Remove="Backups\**\*.cs" />
    <None Include="Backups\**\*" />
  </ItemGroup>

</Project>
